title: Lily Mihalik
portrait: "/static/img/anthony-pesce_crop.jpg"
short_description: Deliberate design thinking
description: Lily Mihalik is a journalist and designer at the Los Angeles Times.
url: "http://lilymihalik.com"
twitter_username: mazet
github_username:  lilymihalik

# Build settings
markdown: kramdown
