title: Anthony Pesce
portrait: "/static/img/anthony-pesce_crop.jpg"
short_description: I write code and words @latimes
description: Anthony Pesce is a journalist and programmer at the Los Angeles Times.
url: "http://anthonypesce.com"
twitter_username: anthonyjpesce
github_username:  anthonyjpesce

# Build settings
markdown: kramdown
